version: "3"

services:
  node:
    image: node:16
    container_name: xp_investimentos
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    command: bash
    restart: always
    # Diretório padrão de execução
    working_dir: /server
    volumes:
      # dentro do diretório /server
      - ./:/server
    # Lista de serviços do qual este serviço depende
    depends_on:
      # Precisa do banco funcionando antes de subir o node
      - db
    # na notação porta_de_fora:porta_de_dentro
    ports:
      - 3000:3000
    # Configura as variáveis de ambiente dentro do container
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db

  # Serviço que irá rodar o banco de dados
  db:
    container_name: xp_investimentos_db
    image: mysql:8.0.21
    restart: always
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão do banco de dados
      - 3310:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password

# Lista de redes que os containeres irão utilizar
networks:
  # Rede padrão, criada automaticamente
  default: